services:
  postgresql:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/data
      - ./initdb:/docker-entrypoint-initdb.d

  minio:
    image: quay.io/minio/minio:latest
    container_name: standup-minio
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  minio-setup:
    image: minio/mc:latest
    depends_on:
      - minio
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO...';
      sleep 2;
      until mc alias set minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do
        sleep 2;
      done;
      mc mb minio/standup-project || echo 'Bucket already exists';
      mc policy set public minio/standup-project;
      echo 'MinIO buckets created successfully';
      "

  superset:
    build:
      context: .
      dockerfile: docker/superset/Dockerfile
    image: standup-superset:latest
    container_name: standup-superset
    restart: unless-stopped
    depends_on:
      - postgresql
    env_file:
      - .env
    environment:
      SUPERSET_ENV: production
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY:-standup-secret-key}
      SUPERSET_DATABASE_URI: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}
      SUPERSET_ADMIN_USER: ${SUPERSET_ADMIN_USER:-admin}
      SUPERSET_ADMIN_PASSWORD: ${SUPERSET_ADMIN_PASSWORD:-admin}
      SUPERSET_ADMIN_EMAIL: ${SUPERSET_ADMIN_EMAIL:-admin@example.com}
    ports:
      - "8088:8088"
    volumes:
      - superset_home:/app/superset_home
    command: >
      /bin/sh -c "
      superset db upgrade &&
      (superset fab create-admin \\
        --username ${SUPERSET_ADMIN_USER:-admin} \\
        --firstname Superset \\
        --lastname Admin \\
        --email ${SUPERSET_ADMIN_EMAIL:-admin@example.com} \\
        --password ${SUPERSET_ADMIN_PASSWORD:-admin} || true) &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088
      "

volumes:
  minio_data:
  postgres_data:
  superset_home:
