[project]
name = "standup-project"
version = "0.1.0"
description = "Pipeline выгрузки аудио из плейстов youtube с последующей транскрибацией, получением списка тем с временными метками, анализ аудио на предмет смеха с получением временных меток."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter",
    "mlx",
    "mlx-metal",
    "mlx-whisper",
    "pandas",
    "psycopg",
    "pydantic",
    "pydantic-settings",
    "yt-dlp",
    "minio",
    "openai>=1.98.0",
]
