[project]
name = "standup-project"
version = "0.1.0"
description = "Pipeline выгрузки аудио из плейстов youtube с последующей транскрибацией, получением списка тем с временными метками, анализ аудио на предмет смеха с получением временных меток."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "connectorx>=0.4.4",
    "dbt-core>=1.10.11",
    "dbt-postgres>=1.9.1",
    "google-genai>=1.36.0",
    "jupyter>=1.1.1",
    "minio>=7.2.16",
    "numba>=0.61.2",
    # "pandas>=2.3.2",
    "parakeet-mlx>=0.3.6",
    "polars>=1.33.1",
    "psycopg>=3.2.9",
    "pyarrow>=21.0.0",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    # "sqlalchemy>=2.0.43",
    "yt-dlp>=2025.8.27",
]
