[project]
name = "standup-project"
version = "0.1.0"
description = "Pipeline выгрузки аудио из плейстов youtube с последующей транскрибацией, получением списка тем с временными метками, анализ аудио на предмет смеха с получением временных меток."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "minio>=7.2.16",
    "numba>=0.61.2",
    "parakeet-mlx>=0.3.6",
    "psycopg>=3.2.9",
    "pydantic-settings>=2.10.1",
    "yt-dlp>=2025.8.27",
]
