version: 2

models:
  - name: dim_date
    description: "Calendar dimension for StandUp DWH analytics marts"
    columns:
      - name: date_id
        description: "Surrogate date identifier in YYYYMMDD format"
        tests:
          - not_null
          - unique
        constraints:
          - type: primary_key
      - name: date
        description: "Calendar date"
        tests:
          - not_null
          - unique
        constraints:
          - type: not_null
          - type: unique
      - name: year
        description: "Year of the date"
      - name: quarter
        description: "Quarter of the date (1-4)"
      - name: month
        description: "Month number"
      - name: month_name
        description: "Month name"
      - name: week_of_year
        description: "Week number within the year"
      - name: day_of_week
        description: "ISO day of week number (1 = Monday)"
      - name: day_name
        description: "Day of week name"
      - name: is_weekend
        description: "Weekend flag"

  - name: dim_channels
    description: "YouTube channel dimension"
    columns:
      - name: channel_id
        description: "Channel primary key (YouTube id)"
        tests:
          - not_null
          - unique
        constraints:
          - type: primary_key
      - name: channel_name
        description: "Channel name"
        tests:
          - not_null
        constraints:
          - type: not_null

  - name: dim_playlists
    description: "YouTube playlist dimension"
    columns:
      - name: playlist_id
        description: "Playlist primary key (YouTube id)"
        tests:
          - not_null
          - unique
        constraints:
          - type: primary_key
      - name: playlist_title
        description: "Playlist title"
        tests:
          - not_null
        constraints:
          - type: not_null

  - name: dim_videos
    description: "Video dimension"
    columns:
      - name: video_id
        description: "Video primary key (YouTube id)"
        tests:
          - not_null
          - unique
        constraints:
          - type: primary_key
      - name: video_title
        description: "Video title"
        tests:
          - not_null
        constraints:
          - type: not_null

  - name: dim_category
    description: "Main content category dimension"
    columns:
      - name: category_id
        description: "Category primary key"
        tests:
          - not_null
          - unique
        constraints:
          - type: primary_key
      - name: main_category
        description: "Category name"
        tests:
          - not_null
          - unique
        constraints:
          - type: not_null
          - type: unique

  - name: dim_subcategory
    description: "Content subcategory dimension"
    columns:
      - name: subcategory_id
        description: "Subcategory primary key"
        tests:
          - not_null
          - unique
        constraints:
          - type: primary_key
      - name: subcategory
        description: "Subcategory name"
        tests:
          - not_null
          - unique
        constraints:
          - type: not_null
          - type: unique

  - name: fact_video_chapters
    description: "Fact table of video chapters with laughter share metrics"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [video_id, subcategory_id, start_s]
    constraints:
      - type: primary_key
        columns: [video_id, subcategory_id, start_s]
    columns:
      - name: video_id
        description: "Foreign key to dim_videos"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_videos')
                field: video_id
        constraints:
          - type: not_null
          - type: foreign_key
            to: ref('dim_videos')
            to_columns: [video_id]
      - name: date_id
        description: "Video load date, foreign key to dim_date"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_date')
                field: date_id
        constraints:
          - type: not_null
          - type: foreign_key
            to: ref('dim_date')
            to_columns: [date_id]
      - name: channel_id
        description: "Foreign key to dim_channels"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_channels')
                field: channel_id
        constraints:
          - type: not_null
          - type: foreign_key
            to: ref('dim_channels')
            to_columns: [channel_id]
      - name: playlist_id
        description: "Foreign key to dim_playlists"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_playlists')
                field: playlist_id
        constraints:
          - type: not_null
          - type: foreign_key
            to: ref('dim_playlists')
            to_columns: [playlist_id]
      - name: subcategory_id
        description: "Foreign key to dim_subcategory"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_subcategory')
                field: subcategory_id
        constraints:
          - type: not_null
          - type: foreign_key
            to: ref('dim_subcategory')
            to_columns: [subcategory_id]
      - name: category_id
        description: "Foreign key to dim_category"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_category')
                field: category_id
        constraints:
          - type: not_null
          - type: foreign_key
            to: ref('dim_category')
            to_columns: [category_id]
      - name: start_s
        description: "Chapter start in seconds"
        tests:
          - not_null
        constraints:
          - type: not_null
      - name: end_s
        description: "Chapter end in seconds"
        tests:
          - not_null
        constraints:
          - type: not_null
      - name: duration
        description: "Chapter duration in seconds"
        tests:
          - not_null
        constraints:
          - type: not_null
      - name: laughter_percent
        description: "Share of chapter time with detected laughter (percent)"

  - name: fact_video_daily_snapshot
    description: "Fact table of daily metric deltas per video"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [video_id, date_id]
    constraints:
      - type: primary_key
        columns: [video_id, date_id]
    columns:
      - name: video_id
        description: "Foreign key to dim_videos"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_videos')
                field: video_id
        constraints:
          - type: not_null
          - type: foreign_key
            to: ref('dim_videos')
            to_columns: [video_id]
      - name: date_id
        description: "Metric snapshot date, foreign key to dim_date"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_date')
                field: date_id
        constraints:
          - type: not_null
          - type: foreign_key
            to: ref('dim_date')
            to_columns: [date_id]
      - name: channel_id
        description: "Foreign key to dim_channels"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_channels')
                field: channel_id
        constraints:
          - type: not_null
          - type: foreign_key
            to: ref('dim_channels')
            to_columns: [channel_id]
      - name: playlist_id
        description: "Foreign key to dim_playlists"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_playlists')
                field: playlist_id
        constraints:
          - type: not_null
          - type: foreign_key
            to: ref('dim_playlists')
            to_columns: [playlist_id]
      - name: prev_day_view
        description: "Change in views compared to the previous day"
      - name: prev_day_like
        description: "Change in likes compared to the previous day"
      - name: prev_day_comment
        description: "Change in comments compared to the previous day"

  - name: fact_video_metrics
    description: "Fact table of final video metrics on load date"
    columns:
      - name: video_id
        description: "Foreign key to dim_videos"
        tests:
          - not_null
          - unique
          - relationships:
              arguments:
                to: ref('dim_videos')
                field: video_id
        constraints:
          - type: primary_key
          - type: foreign_key
            to: ref('dim_videos')
            to_columns: [video_id]
      - name: playlist_id
        description: "Foreign key to dim_playlists"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_playlists')
                field: playlist_id
        constraints:
          - type: not_null
          - type: foreign_key
            to: ref('dim_playlists')
            to_columns: [playlist_id]
      - name: channel_id
        description: "Foreign key to dim_channels"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_channels')
                field: channel_id
        constraints:
          - type: not_null
          - type: foreign_key
            to: ref('dim_channels')
            to_columns: [channel_id]
      - name: date_id
        description: "Video load date, foreign key to dim_date"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_date')
                field: date_id
        constraints:
          - type: not_null
          - type: foreign_key
            to: ref('dim_date')
            to_columns: [date_id]
      - name: view_count
        description: "View count at load time"
      - name: like_count
        description: "Like count at load time"
      - name: comment_count
        description: "Comment count at load time"
      - name: duration
        description: "Video duration in seconds"
        tests:
          - not_null
        constraints:
          - type: not_null
      - name: laughter_percent
        description: "Share of video duration with detected laughter (percent)"
