version: 2
models:
  - name: stg_videos_base
    description: "Staging model with video metadata after expanding JSON video_meta_json and casting for the Core layer"
    columns:
      - name: video_id
        description: "YouTube video identifier"
      - name: channel_id
        description: "YouTube channel identifier"
      - name: channel_name
        description: "Channel name from the primary source"
      - name: playlist_id
        description: "YouTube playlist identifier"
      - name: playlist_title
        description: "Playlist title"
      - name: video_title
        description: "Video title"
      - name: duration
        description: "Video duration in seconds"
      - name: view_count
        description: "View count at extraction time"
      - name: like_count
        description: "Like count at extraction time"
      - name: comment_count
        description: "Comment count at extraction time"
      - name: upload_date
        description: "YouTube publication date"
      - name: meta_updated_at
        description: "Metadata update timestamp set by a trigger (initialized in initdb/init_schema.sql) when the JSON changes"
      - name: process_status
        description: "Technical processing status"
      - name: is_valid
        description: "Row validity flag after pipeline checks"
  - name: stg_transcripts
    description: "Staging model of transcript segments after expanding JSON transcribe_json"
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
            - video_id
            - segment_id
    columns:
      - name: video_id
        description: "YouTube video identifier"
      - name: segment_id
        description: "Transcript segment index within the video"
      - name: segment_text
        description: "Transcript segment text"
      - name: start_s
        description: "Segment start in seconds"
      - name: end_s
        description: "Segment end in seconds"
      - name: is_valid
        description: "Row validity flag after pipeline checks"

  - name: stg_sound_features
    description: "Staging model of laughter episodes after expanding JSON laugh_events_json"
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
            - video_id
            - sequence
    columns:
      - name: video_id
        description: "YouTube video identifier"
      - name: sequence
        description: "Laughter episode counter"
      - name: points
        description: "Number of detector points forming the episode"
      - name: start_seconds
        description: "Laughter episode start in seconds"
      - name: end_seconds
        description: "Laughter episode end in seconds"
      - name: duration_seconds
        description: "Laughter episode duration"
      - name: avg_confidence
        description: "Average confidence of the laughter detection model within the episode"
      - name: max_confidence
        description: "Maximum confidence of the laughter detection model within the episode"
      - name: is_valid
        description: "Row validity flag after pipeline checks"

  - name: stg_chapters
    description: "Staging model of video chapters after expanding JSON llm_chapter_json"
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
            - video_id
            - start_segment_id
            - end_segment_id
    columns:
      - name: video_id
        description: "YouTube video identifier"
      - name: start_segment_id
        description: "Start segment identifier"
      - name: end_segment_id
        description: "End segment identifier"
      - name: chapter_theme
        description: "LLM-generated chapter title"
      - name: chapter_summary
        description: "LLM-generated chapter summary"
      - name: is_valid
        description: "Row validity flag after pipeline checks"
  - name: stg_classifications
    description: "Staging model of chapter classifications after expanding JSON llm_classifier_json"
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
            - video_id
            - start_segment_id
    columns:
      - name: video_id
        description: "YouTube video identifier"
      - name: start_segment_id
        description: "Start segment identifier"
      - name: reason
        description: "LLM explanation for the chosen classification"
      - name: subcategory
        description: "Content subcategory chosen by the LLM"
      - name: main_category
        description: "Main content category chosen by the LLM"
      - name: is_valid
        description: "Row validity flag after pipeline checks"
