version: 2
models:
  - name: stg_videos_base
    description: "Стейджинговая модель с метаданными видео после разворачивания JSON video_meta_json и приведения типов для Core-слоя"
    columns:
      - name: video_id
        description: "Идентификатор YouTube видео"
        tests:
          - not_null
          - unique
      - name: channel_id
        description: "Идентификатор YouTube канала"
      - name: channel_name
        description: "Название канала из первичного источника"
      - name: playlist_id
        description: "Идентификатор YouTube плейлиста"
      - name: playlist_title
        description: "Название плейлиста"
      - name: video_title
        description: "Название видео"
      - name: duration
        description: "Продолжительность видео в секундах"
      - name: view_count
        description: "Количество просмотров на момент выгрузки"
      - name: like_count
        description: "Количество лайков на момент выгрузки"
      - name: comment_count
        description: "Количество комментариев на момент выгрузки"
      - name: upload_date
        description: "Дата публикации видео на YouTube"
      - name: meta_updated_at
        description: "Метка обновления метаданных, устанавливаемая триггером (инициализирована в initdb/init_schema.sql) при изменении JSON"
      - name: process_status
        description: "Технический статус обработки видео"
      - name: is_valid
        description: "Признак валидности строки после проверок пайплайна"

  - name: stg_transcripts
    description: "Стейджинговая модель сегментов транскрипции после разворачивания JSON transcribe_json"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [video_id, segment_id]
    columns:
      - name: video_id
        description: "Идентификатор YouTube видео"
        tests:
          - not_null
      - name: segment_id
        description: "Порядковый номер сегмента транскрипции внутри видео"
        tests:
          - not_null
      - name: segment_text
        description: "Текст сегмента транскрипции"
        tests:
          - not_null
      - name: start_s
        description: "Момент начала сегмента в секундах"
        tests:
          - not_null
      - name: end_s
        description: "Момент окончания сегмента в секундах"
        tests:
          - not_null
      - name: is_valid
        description: "Признак валидности строки после проверок пайплайна"

  - name: stg_sound_features
    description: "Стейджинговая модель эпизодов смеха после разворачивания JSON laugh_events_json"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [video_id, sequence]
    columns:
      - name: video_id
        description: "Идентификатор YouTube видео"
        tests:
          - not_null
      - name: sequence
        description: "Счетчик эпизодов со смехом"
        tests:
          - not_null
      - name: points
        description: "Количество точек детектора, сформировавших эпизод"
        tests:
          - not_null
      - name: start_seconds
        description: "Начало эпизода смеха в секундах"
        tests:
          - not_null
      - name: end_seconds
        description: "Конец эпизода смеха в секундах"
        tests:
          - not_null
      - name: duration_seconds
        description: "Длительность эпизода смеха"
        tests:
          - not_null
      - name: avg_confidence
        description: "Средняя уверенность модели детекции смеха в рамках эпизода"
      - name: max_confidence
        description: "Максимальная уверенность модели детекции смеха в рамках эпизода"
      - name: is_valid
        description: "Признак валидности строки после проверок пайплайна"

  - name: stg_chapters
    description: "Стейджинговая модель глав видео после разворачивания JSON llm_chapter_json"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [video_id, start_segment_id, end_segment_id]
    columns:
      - name: video_id
        description: "Идентификатор YouTube видео"
        tests:
          - not_null
      - name: start_segment_id
        description: "Идентификатор сегмента начала главы"
        tests:
          - not_null
      - name: end_segment_id
        description: "Идентификатор сегмента окончания главы"
        tests:
          - not_null
      - name: chapter_theme
        description: "Название главы, сгенерированное LLM"
        tests:
          - not_null
      - name: chapter_summary
        description: "Краткое описание главы, сгенерированное LLM"
        tests:
          - not_null
      - name: is_valid
        description: "Признак валидности строки после проверок пайплайна"
  - name: stg_classifications
    description: "Стейджинговая модель классификаций глав после разворачивания JSON llm_classifier_json"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [video_id, start_segment_id]
    columns:
      - name: video_id
        description: "Идентификатор YouTube видео"
        tests:
          - not_null
      - name: start_segment_id
        description: "Идентификатор сегмента начала главы"
        tests:
          - not_null
      - name: reason
        description: "Пояснение LLM к выбранной классификации"
        tests:
          - not_null
      - name: subcategory
        description: "Подкатегория контента, выбранная LLM"
        tests:
          - not_null
      - name: main_category
        description: "Основная категория контента, выбранная LLM"
        tests:
          - not_null
      - name: is_valid
        description: "Признак валидности строки после проверок пайплайна"
