version: 2

models:
  - name: dim_channels
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: [channel_id]
    description: "YouTube channel dimension"
    columns:
      - name: channel_id
        description: "Channel primary key (YouTube id)"
        data_type: text
      - name: channel_name
        description: "Channel name"
        data_type: text

  - name: dim_playlists
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: [playlist_id]
    description: "YouTube playlist dimension"
    columns:
      - name: playlist_id
        description: "Playlist primary key (YouTube id)"
        data_type: text
      - name: playlist_title
        description: "Playlist title"
        data_type: text

  - name: dim_videos
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: [video_id]
    description: "Video dimension"
    columns:
      - name: video_id
        description: "Video primary key (YouTube id)"
        data_type: text
      - name: video_title
        description: "Video title"
        data_type: text


  - name: dim_category
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: [category_id]
    description: "Main content category dimension"
    columns:
      - name: category_id
        description: "Category primary key"
        data_type: smallint
      - name: main_category
        description: "Category name"
        data_type: text

  - name: dim_subcategory
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: [subcategory_id]
    description: "Content subcategory dimension"
    columns:
      - name: subcategory_id
        description: "Subcategory primary key"
        data_type: smallint
      - name: subcategory
        description: "Subcategory name"
        data_type: text

  - name: fact_video_chapters
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: [video_id, subcategory_id, start_s]
      - type: foreign_key
        columns: [video_id]
        to: ref('dim_videos')
        to_columns: [video_id]
      - type: foreign_key
        columns: [channel_id]
        to: ref('dim_channels')
        to_columns: [channel_id]
      - type: foreign_key
        columns: [playlist_id]
        to: ref('dim_playlists')
        to_columns: [playlist_id]
      - type: foreign_key
        columns: [subcategory_id]
        to: ref('dim_subcategory')
        to_columns: [subcategory_id]
      - type: foreign_key
        columns: [category_id]
        to: ref('dim_category')
        to_columns: [category_id]
      - type: not_null
        columns: [start_s, end_s, duration]
    description: "Fact table of video chapters with laughter share metrics"
    columns:
      - name: video_id
        description: "Foreign key to dim_videos"
        data_type: text
      - name: date_id
        description: "Video load date, foreign key to dim_date"
        data_type: int
      - name: channel_id
        description: "Foreign key to dim_channels"
        data_type: text
      - name: playlist_id
        description: "Foreign key to dim_playlists"
        data_type: text
      - name: subcategory_id
        description: "Foreign key to dim_subcategory"
        data_type: smallint
      - name: category_id
        description: "Foreign key to dim_category"
        data_type: smallint
      - name: start_s
        description: "Chapter start in seconds"
        data_type: float
      - name: end_s
        description: "Chapter end in seconds"
        data_type: float
      - name: duration
        description: "Chapter duration in seconds"
        data_type: numeric
      - name: laughter_percent
        description: "Share of chapter time with detected laughter (percent)"
        data_type: numeric

  - name: fact_video_daily_snapshot
    description: "Fact table of daily metric deltas per video"
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: [video_id, date_id]
      - type: foreign_key
        columns: [video_id]
        to: ref('dim_videos')
        to_columns: [video_id]
      - type: foreign_key
        columns: [channel_id]
        to: ref('dim_channels')
        to_columns: [channel_id]
      - type: foreign_key
        columns: [playlist_id]
        to: ref('dim_playlists')
        to_columns: [playlist_id]
    columns:
      - name: video_id
        description: "Foreign key to dim_videos"
        data_type: text
      - name: date_id
        description: "Metric snapshot date, foreign key to dim_date"
        data_type: int
      - name: channel_id
        description: "Foreign key to dim_channels"
        data_type: text
      - name: playlist_id
        description: "Foreign key to dim_playlists"
        data_type: text
      - name: prev_day_view
        description: "Change in views compared to the previous day"
        data_type: bigint
      - name: prev_day_like
        description: "Change in likes compared to the previous day"
        data_type: bigint
      - name: prev_day_comment
        description: "Change in comments compared to the previous day"
        data_type: bigint

  - name: fact_video_metrics
    description: "Fact table of final video metrics on load date"
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: [video_id, date_id]
      - type: foreign_key
        columns: [video_id]
        to: ref('dim_videos')
        to_columns: [video_id]
      - type: foreign_key
        columns: [playlist_id]
        to: ref('dim_playlists')
        to_columns: [playlist_id]
      - type: foreign_key
        columns: [channel_id]
        to: ref('dim_channels')
        to_columns: [channel_id]
    columns:
      - name: video_id
        description: "Foreign key to dim_videos"
        data_type: text
      - name: playlist_id
        description: "Foreign key to dim_playlists"
        data_type: text
      - name: channel_id
        description: "Foreign key to dim_channels"
        data_type: text
      - name: date_id
        description: "Video load date, foreign key to dim_date"
        data_type: int
      - name: view_count
        description: "View count at load time"
        data_type: int
      - name: like_count
        description: "Like count at load time"
        data_type: int
      - name: comment_count
        description: "Comment count at load time"
        data_type: int
      - name: duration
        description: "Video duration in seconds"
        data_type: int
      - name: laughter_percent
        description: "Share of video duration with detected laughter (percent)"
        data_type: DECIMAL
