version: 2

models:
  - name: chapters_metrics
    description: "Intermediate mart with video chapter metrics and calendar dimensions"
    columns:
      - name: main_category
        description: "Main content category"
        tests:
          - not_null
      - name: subcategory
        description: "Content subcategory"
        tests:
          - not_null
      - name: video_title
        description: "Video title"
        tests:
          - not_null
      - name: channel_name
        description: "Channel name"
        tests:
          - not_null
      - name: playlist_title
        description: "Playlist title"
      - name: duration
        description: "Chapter duration in seconds"
      - name: laughter_percent
        description: "Share of laughter within the chapter (percent of duration)"
      - name: date
        description: "Calendar date"
        tests:
          - not_null
      - name: year
        description: "Calendar year"
      - name: quarter
        description: "Calendar quarter (1-4)"
      - name: month
        description: "Month number"
      - name: month_name
        description: "Month name"
      - name: week_of_year
        description: "Week number within the year"
      - name: day_of_week
        description: "ISO day of week number"
      - name: day_name
        description: "Day of week name"
      - name: is_weekend
        description: "Weekend flag"

  - name: video_metrics
    description: "Marketing mart of final video metrics with classification attributes"
    columns:
      - name: channel_name
        description: "Channel name"
        tests:
          - not_null
      - name: playlist_title
        description: "Playlist title"
      - name: video_title
        description: "Video title"
        tests:
          - not_null
      - name: subcategory
        description: "Content subcategory"
        tests:
          - not_null
      - name: main_category
        description: "Main content category"
      - name: view_count
        description: "View count at the latest snapshot"
      - name: laughter_percent
        description: "Share of video duration with recorded laughter"
      - name: like_count
        description: "Like count at the latest snapshot"
      - name: comment_count
        description: "Comment count at the latest snapshot"
      - name: duration
        description: "Video duration in seconds"
      - name: duration_hms
        description: "Video duration in HH:MM:SS format"
      - name: date
        description: "Video upload date"
        tests:
          - not_null
      - name: year
        description: "Video upload year"
      - name: quarter
        description: "Video upload quarter (1-4)"
      - name: month
        description: "Upload month number"
      - name: month_name
        description: "Upload month name"
      - name: week_of_year
        description: "Upload week number"
      - name: day_of_week
        description: "ISO day of week number for the upload"
      - name: day_name
        description: "Upload day of week name"
      - name: is_weekend
        description: "Flag indicating the video was uploaded on a weekend"

  - name: video_daily_snapshot
    description: "Daily change mart for views, likes, and comments per video"
    columns:
      - name: video_title
        description: "Video title"
        tests:
          - not_null
      - name: channel_name
        description: "Channel name"
        tests:
          - not_null
      - name: playlist_title
        description: "Playlist title"
      - name: prev_day_view
        description: "Change in views vs. previous day"
      - name: prev_day_like
        description: "Change in likes vs. previous day"
      - name: prev_day_comment
        description: "Change in comments vs. previous day"
      - name: date_id
        description: "Snapshot date as surrogate key YYYYMMDD"
        tests:
          - not_null
      - name: date
        description: "Snapshot calendar date"
      - name: year
        description: "Calendar year"
      - name: quarter
        description: "Calendar quarter (1-4)"
      - name: month
        description: "Month number"
      - name: month_name
        description: "Month name"
      - name: week_of_year
        description: "Week number within the year"
      - name: day_of_week
        description: "ISO day of week number"
      - name: day_name
        description: "Day of week name"
      - name: is_weekend
        description: "Weekend flag"

  - name: dwh_statistics
    description: "Summary report with aggregated counters across DWH marts"
    columns:
      - name: label
        description: "Metric label"
        tests:
          - not_null
      - name: total
        description: "Metric value"
